output_path = "target/JavaFx-Index.db",
resource_paths = [
    "sample_projects/jfx/jfx-master/modules/javafx.base/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.controls/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.fxml/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.graphics/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.media/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.swing/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.swt/src/main/java",
    "sample_projects/jfx/jfx-master/modules/javafx.web/src/main/java"
]
allowed_packages = [
    "javafx.animation",
    "javafx.application",
    "javafx.beans",
    "javafx.beans.binding",
    "javafx.beans.property",
    "javafx.beans.property.adapter",
    "javafx.beans.value",
    "javafx.collections",
    "javafx.collections.transformation",
    "javafx.concurrent",
    "javafx.css",
    "javafx.css.converter",
    "javafx.embed.swing",
    "javafx.event",
    "javafx.fxml",
    "javafx.geometry",
    "javafx.print",
    "javafx.scene",
    "javafx.scene.canvas",
    "javafx.scene.chart",
    "javafx.scene.control",
    "javafx.scene.control.cell",
    "javafx.scene.control.skin",
    "javafx.scene.effect",
    "javafx.scene.image",
    "javafx.scene.input",
    "javafx.scene.layout",
    "javafx.scene.media",
    "javafx.scene.paint",
    "javafx.scene.robot",
    "javafx.scene.shape",
    "javafx.scene.text",
    "javafx.scene.transform",
    "javafx.scene.web",
    "javafx.stage",
    "javafx.util",
    "javafx.util.converter"
]
build_files = ["sample_projects/jfx/jfx-master/build.gradle"]
maven_home = "/opt/maven"
