output_path = "target/Paper-Api-Index.db"
resource_paths = ["indexes/paper/Paper-API/src/main/java"] #, "indexes/paper/Paper-Server/src/main/java"]
allowed_packages = [
    "*"
]
build_files = [
    "indexes/paper/test-plugin/build.gradle.kts",
    "indexes/paper/Paper-MojangAPI/build.gradle.kts",
    "indexes/paper/Paper-API/build.gradle.kts",
    "indexes/paper/build.gradle.kts",
    "indexes/paper/settings.gradle.kts"
]
maven_home = "/opt/maven"
