output_path = "target/ApFloat-Index.db"
resource_paths = ["indexes/apfloat/apfloat/src/main/java"]
allowed_packages = ["*"]
build_files = [
    "indexes/apfloat/apfloat/pom.xml"
]
maven_home = "/opt/maven"
